source 'https://github.com/CocoaPods/Specs.git'
source 'http://192.168.0.169/App/SpecsRepo_iOS.git' 
use_frameworks!

platform :ios, '8.0'

target 'DJMoudlePersonal_Example' do
  pod 'DJMoudlePersonal', :path => '../'
  pod 'DJBase', '~> 1.0.1'
  target 'DJMoudlePersonal_Tests' do
    inherit! :search_paths

    
  end
end
